In [1]:
import pandas as pd
import numpy as np

In [2]:
x = pd.read_csv('./sourcedata/cortex_svz_cellcentroids.csv')

In [7]:
x['Region'].unique()

array(['Cortex', 'SVZ', 'Choroid Plexus'], dtype=object)

In [3]:
y = pd.read_csv('./sourcedata/cortex_svz_counts.csv')

In [4]:
y.head()

1700022a21rik  1700025g04rik  4933401b06rik  5830417i10rik  9330102e08rik  \
0              3              1              2              0              1   
1              1              0              0              0              0   
2              0              0              1              1              0   
3              0              0              0              0              0   
4              0              0              0              1              0   

   9430018g01rik  9430083a17rik  Aanat  Aasdh  Aatf  ...  Tyrp1  Ubqlnl  \
0              1              1      0      2     0  ...      0       0   
1              0              0      0      0     0  ...      1       1   
2              0              0      0      0     0  ...      2       2   
3              0              0      0      0     1  ...      0       0   
4              1              1      0      3     0  ...      1       0   

   Ptgdr  P2ry4  Prdm6  Pde6b  Zp1  Dlx4  Opn1sw  Pramef12  
0      1      0      0      0    0     0       0         1  
1      0      1      1      0    0     0       0         0  
2      1      1      0      0    1     0       1         0  
3      0      0      0      0    0     0       0         0  
4      0      1      0      0    0     1       0         0  

[5 rows x 10000 columns]

In [5]:
z = pd.read_csv('./sourcedata/RNA_locations_cell_cortex/RNA_locations_cell_4.csv')

In [6]:
y.shape

(913, 10000)

In [7]:
rnaseq = pd.read_csv('GSE71585_RefSeq_counts.csv.gz')

In [8]:
rnaseq.head()

gene  Calb2_tdTpositive_cell_1  Calb2_tdTpositive_cell_2  \
0  0610005C13Rik                      0.00                      0.00   
1  0610007C21Rik                    992.00                   2287.02   
2  0610007L01Rik                      2.57                    177.00   
3  0610007N19Rik                      0.00                      0.00   
4  0610007P08Rik                      0.00                      0.00   

   Calb2_tdTpositive_cell_3  Calb2_tdTpositive_cell_4  \
0                      0.00                       0.0   
1                    491.78                    1932.0   
2                      0.00                       1.0   
3                      0.00                       0.0   
4                      0.00                       0.0   

   Calb2_tdTpositive_cell_5  Calb2_tdTpositive_cell_6  \
0                       0.0                      0.00   
1                    1425.0                    130.03   
2                       2.0                      3.00   
3                       0.0                      0.00   
4                       0.0                      0.00   

   Calb2_tdTpositive_cell_7  Calb2_tdTpositive_cell_8  \
0                      0.00                       0.0   
1                   2110.02                     955.0   
2                   3040.99                     101.0   
3                      0.00                       0.0   
4                     17.03                       0.0   

   Calb2_tdTpositive_cell_9  ...  CAV_VISp_Contra_tdTpos_cell_5  \
0                       0.0  ...                           0.00   
1                     326.0  ...                         352.06   
2                       0.0  ...                         367.00   
3                       0.0  ...                           0.00   
4                       0.0  ...                           3.00   

   Rbp4_CTX_10pg_1  Rbp4_CTX_10pg_2  Rbp4_CTX_10pg_3  Rbp4_CTX_10pg_4  \
0              0.0             0.00              0.0              0.0   
1            401.0          1750.99           1463.0           3439.0   
2            242.0             1.00             69.0              0.0   
3              0.0             0.00              0.0              0.0   
4             11.0             0.00              0.0              0.0   

   Rbp4_CTX_10pg_5  Rbp4_CTX_10pg_6  Rbp4_CTX_250ng_1  Rbp4_CTX_250ng_2  \
0             0.00             0.00              8.00              9.00   
1           502.95          1486.36            956.40           1054.94   
2            53.00            40.15           1251.00           1356.20   
3           704.01             0.00             27.00             37.00   
4             0.00             0.00            574.35            570.86   

   Trib2_CTX_250ng_1  
0               5.00  
1             944.03  
2            1147.00  
3              35.00  
4             590.84  

[5 rows x 1810 columns]

In [13]:
genes, comm1, comm2 = np.intersect1d(rnaseq['gene'].values, y.columns, return_indices = True)

In [14]:
comm1

array([ 1908,  1945,  1961, ..., 23323, 23324, 23325])

In [15]:
comm2

array([7148, 8339, 9818, ..., 3333, 9700, 4391])

In [16]:
genes

array(['A1cf', 'A3galt2', 'A4galt', ..., 'Zyx', 'Zzef1', 'Zzz3'],
      dtype=object)

In [45]:
fish_shared = y.values[:, comm2]
rna_shared = rnaseq.values[comm1, 1:].T.astype(np.float32)

In [40]:
import h5py

In [37]:
coords = x[['X', 'Y']].values

In [38]:
coords.shape

(913, 2)

In [57]:
#f = h5py.File('cortex_svz_combined.hdf5', 'w')

In [56]:
#f.create_dataset("fish_shared", data = fish_shared)
#f.create_dataset("rna_shared", data = rna_shared)
#f.create_dataset("coords", data = coords)
#f.create_dataset("genes", data = genes.astype(str))
#f.close()

In [59]:
f = h5py.File('cortex_svz_combined.hdf5','r')

In [61]:
np.vstack((f['fish_shared'],f['rna_shared'])).shape

(2722, 9541)

In [65]:
f['rna_shared'].shape[0]

1809

In [67]:
z_init = f['coords']
zvar_init = np.random.normal(np.mean(z_init, axis = 0), np.var(z_init, axis = 0), size = (1809, 2))

In [68]:
zvar_init

array([[   5390.94588061, -314370.75053569],
       [ -36131.61173979, -248999.53826286],
       [ 462297.19393533,  -77076.46211163],
       ...,
       [-175309.60527432, -120711.90531892],
       [ 198875.63682724,  -25158.44598109],
       [ 601653.49086585,  -25126.96308198]])

In [71]:
np.mean(z_init, axis = 0)

array([1048.55005476,  986.94913472])

In [73]:
np.min(z_init, axis = 0)

array([103.12, 122.03])

In [75]:
np.max(z_init)

1960.0